Решение задачи №3
plyul/go-course pull request #14
Opened 2020-11-24 18:10 UTC by plyul

Добавлен пакет для парсинга текстовго файла и наивная реализация поиcка Top10

2020-11-25 08:17 UTC, korjavin requested changes

2020-11-25 08:17 UTC, korjavin commented on task3/main.go
> +	f, err := os.Open(args[1])
+1

2020-11-25 08:17 UTC, korjavin commented on task3/main.go
> +	var w string
а для чего это объявление?

2020-11-25 08:17 UTC, korjavin commented on task3/main.go
> +			wordFreqs[w]++
функционал wordFreqs и wordAppear я бы объединил в пакет

2020-11-25 08:17 UTC, korjavin commented on task3/main.go
> +			break
Не лучшее решение использовать "магическое" значение "".

Скорее, подошла бы идиома word, closed:=....

2020-11-25 08:17 UTC, korjavin commented on task3/parser/parser_test.go
> +	f, err := os.Open("test_cut.txt")
Такие файлы принято размещать в testdata каталоге в пакете

2020-11-25 08:17 UTC, korjavin commented on task3/parser/parser_test.go
> +	var testSequence = []struct {
А просто []string не подошло бы?

2020-11-25 08:17 UTC, korjavin commented on task3/parser/parser.go
> +func (p *TextParser) Scan() string {
В тексте.
I like this very much.
Do you like this?

this находится в конце предложения и должно быть исключено из рейтинга.
Можешь добавить это как testcase?

2020-11-26 06:01 UTC, plyul commented on task3/parser/parser.go
> +func (p *TextParser) Scan() string {
Добавлено https://github.com/plyul/go-course/pull/14/commits/361b2d380bde548a971634d6023b70743dddcde6#diff-d4fdd889bdc1ba48541ae999655cc472ebdbc5b5956f3dd6fd5a8b4021a3e005L14

2020-12-01 10:01 UTC, korjavin requested changes

2020-12-01 10:01 UTC, korjavin commented on task3/internal/textparser/textparser.go
> +		if strings.Contains(w, ".") { // слово содержит точку, т.е. оно на границе предложения
has prefix?

2020-12-01 10:01 UTC, korjavin commented on task3/internal/wordsprovider/defs.go
> +type WordsProvider interface {
И тут тоже нет кода

2020-12-01 10:03 UTC, plyul commented on task3/internal/sortedmap/sortedmap.go
> +	sort.Slice(words, func(i, j int) bool {
Да, по порядку появления в тексте.

2020-12-01 10:27 UTC, plyul commented on task3/internal/sortedmap/sortedmap_test.go
> +
https://github.com/plyul/go-course/pull/14/commits/dc810b4cdbf113f9da4adf4d3fe0a82be3d92a79#diff-a8c03e1148352cdc2ea2c2628bd675c05f71a250322172a68fec6570cff25b8cR30

2020-12-01 10:39 UTC, plyul commented on task3/internal/wordsprovider/defs.go
> +type WordsProvider interface {
Вот тут мне непонятно, куда ложить интерфейс.

Если бы не было констант, можно было бы положить в wordscounter, как пользователя интерфейса.
Но т.к. есть константы, и вроде как логично держать полное определение интерфейса (константы и тип) в одном месте, то выделил всё это в отдельный файл.
Константы используются как wordscounter, так и textparser (и любой другой реализацией интерфейса wordsprovider), из-за констант ставить в зависимость друг-друга эти пакеты не хотелось бы.

2020-12-01 10:40 UTC, plyul commented on task3/internal/wordscounter/wordscounter.go
> +	bannedWords := map[string]bool{}
https://github.com/plyul/go-course/pull/14/commits/dc810b4cdbf113f9da4adf4d3fe0a82be3d92a79#diff-24cd42b010062aa55f0d7739625f33ab172468dfa05070a116b839a05ff4f9b7R30

2020-12-01 10:41 UTC, plyul commented on task3/cmd/topcnt/main.go
> +	const (
https://github.com/plyul/go-course/pull/14/commits/dc810b4cdbf113f9da4adf4d3fe0a82be3d92a79#diff-e2943f7c5ba378472dcfa97fbf2c06a2bffab1d9c5fb3504a09d5aa3339898deR1

2020-12-01 10:42 UTC, plyul commented on task3/cmd/topcnt/main.go
> +	const (
Вынес конфигурирование в отдельный пакет

2020-12-01 10:42 UTC, plyul commented on task3/cmd/topcnt/main.go
> +	const (
Константы сверху

2020-12-01 10:43 UTC, plyul commented on task3/internal/sortedmap/sortedmap.go
> +	_, keyIsPresent := sm.wordCounters[key]
https://github.com/plyul/go-course/pull/14/commits/dc810b4cdbf113f9da4adf4d3fe0a82be3d92a79#diff-8d8eca5ce551b4a73d22fe24abf41838a75620e9a3755bd5c71f30e19f86bb15R37

2020-12-01 10:44 UTC, plyul commented on task3/internal/textparser/textparser.go
> +		if strings.Contains(w, ".") { // слово содержит точку, т.е. оно на границе предложения
Исправлено тут https://github.com/plyul/go-course/pull/14/commits/00f8615755da25f32b16dfa8ae3cd37e19985a8f#diff-6faf465cb2f95dce3844e59a6f95d2c419a7d15cdd57883c42573645df07366cR68

2020-12-01 10:45 UTC, plyul commented on task3/internal/cfg/config.go
> +package cfg
Вынес конфигурирование в отдельный пакет

2020-12-01 11:09 UTC, korjavin commented on task3/internal/wordsprovider/defs.go
> +type WordsProvider interface {
Мне кажется что wordtag используется только в  TextParser.

2020-12-01 11:33 UTC, plyul commented on task3/internal/wordsprovider/defs.go
> +type WordsProvider interface {
В wordscounter тоже используется https://github.com/plyul/go-course/pull/14/files#diff-24cd42b010062aa55f0d7739625f33ab172468dfa05070a116b839a05ff4f9b7R28

2020-12-01 11:40 UTC, korjavin commented on task3/internal/wordsprovider/defs.go
> +type WordsProvider interface {
А, точно. Хорошо, оставим так, ещё подумаем.

2020-12-01 11:40 UTC, korjavin approved these changes

2020-12-01 12:07 UTC, plyul commented on task3/internal/cfg/config.go
> +package cfg
Перекомпоновал программу, чтобы конфиг был в пакете того, кого он конфигурирует.
https://github.com/plyul/go-course/pull/14/commits/e453838b1b1271eed1d1d8c3b08ebf613290a9dd

2020-12-01 12:15 UTC, korjavin approved these changes

2020-12-01 12:26 UTC, merged