SortedList implementation
plyul/go-course pull request #8
Opened 2020-11-18 09:57 UTC by plyul

2020-11-19 11:09 UTC, korjavin requested changes

2020-11-19 11:09 UTC, korjavin commented on task2/sarray/sarray_test.go
> +// go test -bench='DeleteOne' .
рекомендую -benchmem добавить

2020-11-19 11:09 UTC, korjavin commented on task2/sarray/sarray_test.go
> +func BenchmarkSortedArray_DeleteOne150k(b *testing.B) { benchmarkSortedArray_DeleteOne(150000, b) }
Сравним результаты бенчмарков?

2020-11-19 20:22 UTC, korjavin commented on task2/slist/slist.go
> +func New() SortedList {
Кажется лучше вернуть указатель.

2020-11-19 20:24 UTC, korjavin commented on task2/slist/slist.go
> +	for l.deleteOne(v) {
Подумай, какая тут возможно оптимизация, и какие вообще проблемы в этом подходе.

2020-11-19 20:25 UTC, korjavin commented on task2/slist/slist.go
> +		return 0, errors.New("list is empty")
как снаружи работать с этим error ? как его сравнить с чем тт?

это не к этому PR , а на подумать

2020-11-19 20:27 UTC, korjavin approved these changes

2020-11-21 04:32 UTC, plyul commented on task2/slist/slist.go
> +func New() SortedList {
Исправлено в https://github.com/plyul/go-course/pull/8/commits/0dd3f0af6541717ad3a8298d0d6f8f6382fcf01a

2020-11-21 04:34 UTC, plyul commented on task2/slist/slist.go
> +	for l.deleteOne(v) {
Непонятно, зачем я так сделал)
Исправлено в https://github.com/plyul/go-course/pull/8/commits/0dd3f0af6541717ad3a8298d0d6f8f6382fcf01a

2020-11-21 05:11 UTC, plyul commented on task2/sarray/sarray_test.go
> +func BenchmarkSortedArray_DeleteOne150k(b *testing.B) { benchmarkSortedArray_DeleteOne(150000, b) }
Сравнил: https://gist.github.com/plyul/666bf5ae49d7abe4f6dfa67d259017a2
Выводы:
1. Sequental scan для вставки и удаления в список выполняется значительно дольше функции getIndex в реализации с массивом. Insert и Delete в массив быстрей, чем в связанный список.

2020-11-21 05:18 UTC, plyul commented on task2/sarray/sarray_test.go
> +// go test -bench='DeleteOne' .
Добавил https://github.com/plyul/go-course/pull/8/commits/1df4e0bde5fdd1d5c8ce039ca0644c0cfa9bddf5

2020-11-21 05:19 UTC, plyul commented on task2/sarray/sarray_test.go
> +// go test -bench='DeleteOne' .
Добавил https://github.com/plyul/go-course/pull/8/commits/1df4e0bde5fdd1d5c8ce039ca0644c0cfa9bddf5

2020-11-21 05:34 UTC, merged